services:
  - type: web
    name: aplicacion-de-sgi-1
    runtime: static
    repo: https://github.com/AgustinWojtyszyn/Aplicacion_de_SGI
    branch: main
    autoDeployTrigger: checksPass
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate"
