services:
  - type: web
    name: ep-consultora
    runtime: static
    autoDeployTrigger: commit
    buildCommand: rm -rf dist && npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
